title: Geometry Seminar @ Texas A&M
logoA: /assets/img/weak_order.png
logoB: /assets/img/bloch.gif
description: A website for the geometry seminar at Texas A&M.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
